#!/bin/bash

# Add custom binaries to path
export PATH="/home/linolium/bin:$PATH"

# Run the GPG agent
envfile="${HOME}/.gnupg/gpg-agent.env"
if test -f "$envfile" && kill -0 $(grep GPG_AGENT_INFO "$envfile" | cut -d: -f 2) 2>/dev/null; then
	eval "$(cat "$envfile")"
else
	eval "$(gpg-agent --daemon --write-env-file "$envfile")"
fi
export GPG_AGENT_INFO

# Start a terminal right off the bat
urxvt &

# Set the wallpaper
feh --bg-scale .wallpaper.jpg &

# Cache binaries for dmenu
bin-list >| /tmp/linolium-dmenu &

# Set up an icon tray (alignment, size, background, window type)
if [ $(hostname) == "ginko" ]; then
	trayerargs --align left --margin 1884
elif [ $(hostname) == "jimmy" ]; then
	trayerargs --align left --margin 1419
fi

# Required for GTK themes to look nice
#gnome-settings-daemon &
xsettingsd &

# Daemon for adjusting volume
# xfconf-query -c xfce4-mixer -p /active-track --create -t string -s "Master"
xfce4-volumed &

# Start MPD daemon
mpd &

# Unlock the keyring and start the gnome keyring daemon
eval `gnome-keyring-daemon`
export GNOME_KEYRING_SOCKET
export GNOME_KEYRING_PID
echo 'BlahBlah103' | pam-keyring-tool -u -s &

# Try and start synergy on startup
if [ $(hostname) == "ginko" ]; then
	(killall synergyc >/dev/null; nohup synergyc -1 ginko >/dev/null 2>/dev/null) &
elif [ $(hostname) == "jimmy" ]; then
	synergys &
fi

# Start redshift
if [ $(hostname) == "ginko" ]; then
	redshift -l 49.2618:-123.2415 -t 6500:5000 &
elif [ $(hostname) == "jimmy" ]; then
	redshift -l 49.2618:-123.2415 -t 6500:4500 &
fi

# Keyboard stuff
(xmodmap -pke > .xmodmap.reset && xmodmap .xmodmap) &
xset r rate 220 27 &

# Special key bindings
#xbindkeys &

## Horizontal and vertical scrolling with trackpoint
xinput set-int-prop "TPPS/2 IBM TrackPoint" "Evdev Wheel Emulation" 8 1
xinput set-int-prop "TPPS/2 IBM TrackPoint" "Evdev Wheel Emulation Button" 8 2
xinput set-int-prop "TPPS/2 IBM TrackPoint" "Evdev Wheel Emulation Axes" 8 6 7 4 5

# Tray
nm-applet &

# Set default cursor
xsetroot -cursor_name left_ptr

# Start SCIM for Chinese input
#export XMODIFIERS=@im=SCIM
#export GTK_IM_MODULE="scim"
#export QT_IM_MODULE="scim"
#scim -d

# Start IBus for Chinese input
export XMODIFIERS=@im=ibus
export GTK_IM_MODULE=ibus
export QT_IM_MODULE=ibus
ibus-daemon -d -x --xim

# Window manager
#exec ck-launch-session xmonad
exec xmonad
